### ISSUE TITLE
Property is set as system property rather than project property

### ISSUE THREAD

**Issue by rcauble** [rynr/user-id-maven-plugin#29]
I am having issues trying to get the property to expand -- when I reference as ${user.id} it doesn't expand it. I wonder if it needs to be specified as a project property instead:

https://stackoverflow.com/questions/7553530/set-maven-property-from-plugin

**Comment by rynr** [comment]
Hello Rob.

Sorry, I wasn't active on Github, so I missed your issue for almost 2 years.
I never had issues using the reverence. Can you provide an example?

Regards,
Rainer

**Comment by rcauble** [comment]
Hi, no worries. I honestly can't remember the context at all now. Feel free to close this out.
