### ISSUE TITLE
Check if the class UnixSystem provides the interesting values

### ISSUE THREAD

**Issue by rynr** [rynr/user-id-maven-plugin#3]
There's a class `com.sun.security.auth.module.UnixSystem` that seems to provide the user-id.  
Unfortunately it's only available with jdk 1.8, so check if this is a valid way to deal with the issue.

**Comment by vjkoskela** [comment]
Ran into your project via Stackoverflow. Great work! 

It would appear that `UnixSystem` is indeed what you are looking for to avoid parsing `/etc/passwd` directly.

Ref:
https://docs.oracle.com/javase/9/docs/api/index.html?com/sun/security/auth/module/UnixSystem.html

**Comment by rynr** [comment]
JDK7 is still supported until July 2022, but creating a major version update would be fine with the note to still use 1 for JDK7.

Trying to use it, I got a warning:  
`Access restriction: The type 'UnixSystem' is not API (restriction on required library '…/jre/lib/rt.jar')`
Need to read what this means, but the code now is nearly nothing at all.

**Comment by rynr** [comment]
So, that class could vanish in any newer version, so I'd not go with that solution even though it's really easier.
Reading the password file is probably not the best version but a relying one, so I close this ticket.

**Comment by vjkoskela** [comment]
You are correct there are fewer API guarantees in the `com.sun` package. However, I'm not sure that it's anymore brittle than already depending on `/etc/passwd`. Further, it's already supported in many versions:

* [Oracle JDK8](https://docs.oracle.com/javase/8/docs/jre/api/security/jaas/spec/com/sun/security/auth/module/UnixSystem.html)
* [Oracle JDK11](https://docs.oracle.com/en/java/javase/11/docs/api/jdk.security.auth/com/sun/security/auth/module/UnixSystem.html)
* [Oracle JDK14](https://docs.oracle.com/en/java/javase/14/docs/api/jdk.security.auth/com/sun/security/auth/module/UnixSystem.html)

It appears in the [Open JDK](https://github.com/openjdk-mirror/jdk7u-jdk/blob/master/src/share/classes/com/sun/security/auth/module/UnixSystem.java) and the [Adopt Open JDK](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/jdk.security.auth/share/classes/com/sun/security/auth/module/UnixSystem.java) as well. I don't think it's going away anytime soon.

However, the problem you found regarding API restrictions may be more difficult to overcome for a Maven plugin. I assume that error message was for JDK8 (or newer)?

Looks like you closed the issue.
